name: deathTP
version: '1.0'
main: jp.zaemongames.deathtp.DeathTP
authors: [ ZaemonGames ]
description: Teleport to death location plugin.
website: https://github.com/ZaemonGames/deathTP
depend:
  - Vault

commands:
  death:
    description: Teleport to death location.
    permission: deathtp.player

permissions:
  deathtp.teleport:
    description: teleport
    default: true
  deathtp.free:
    description: free teleport
    default: false
